-- Query 1 (Display each store with its city and country)
SELECT s.store_id AS "STORE ID", ci.city AS "CITY", co.country AS "COUNTRY" FROM store s JOIN address a ON s.address_id = a.address_id JOIN city ci ON a.city_id = ci.city_id JOIN country co ON ci.country_id = co.country_id;

-- Query 2 (Calculate total revenue generated by each store)
SELECT s.store_id AS "STORE ID", SUM(p.amount) AS "TOTAL REVENUE" FROM store s JOIN staff st ON s.store_id = st.store_id JOIN payment p ON st.staff_id = p.staff_id GROUP BY s.store_id;

-- Query 3 (Average film length by category)
SELECT c.name AS "CATEGORY", AVG(f.length) AS "AVG LENGTH" FROM category c JOIN film_category fc ON c.category_id = fc.category_id JOIN film f ON fc.film_id = f.film_id GROUP BY c.name;

-- Query 4 (Film categories with the longest average duration)
SELECT c.name AS "CATEGORY", AVG(f.length) AS "AVG LENGTH" FROM category c JOIN film_category fc ON c.category_id = fc.category_id JOIN film f ON fc.film_id = f.film_id GROUP BY c.name ORDER BY "AVG LENGTH" DESC;

-- Query 5 (Most frequently rented movies in descending order)
SELECT f.title AS "TITLE", COUNT(r.rental_id) AS "RENTAL COUNT" 
FROM film f 
JOIN inventory i 
ON f.film_id = i.film_id 
JOIN rental r ON i.inventory_id = r.inventory_id 
GROUP BY f.title 
ORDER BY "RENTAL COUNT" 
DESC;

-- Query 6 (Top five genres by gross revenue)
SELECT c.name AS "CATEGORY", SUM(p.amount) AS "TOTAL REVENUE" FROM category c JOIN film_category fc ON c.category_id = fc.category_id JOIN inventory i ON fc.film_id = i.film_id JOIN rental r ON i.inventory_id = r.inventory_id JOIN payment p ON r.rental_id = p.rental_id GROUP BY c.name ORDER BY "TOTAL REVENUE" DESC LIMIT 5;

-- Query 7 (Check if "Academy Dinosaur" is available for rent in Store 1)
SELECT f.title AS "TITLE", i.store_id AS "STORE ID", COUNT(i.inventory_id) - COUNT(r.rental_id) AS "AVAILABLE COPIES" FROM film f JOIN inventory i ON f.film_id = i.film_id LEFT JOIN rental r ON i.inventory_id = r.inventory_id AND r.return_date IS NULL WHERE f.title = 'Academy Dinosaur' AND i.store_id = 1 GROUP BY f.title, i.store_id;